apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image: myrepo/ingestion-service:latest
          env:
            - name: GRPC_ENABLED
              value: "true"
            - name: HTTP_ENABLED
              value: "false"
            - name: MQTT_ENABLED
              value: "true"
